Settings/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
      path('admin/', admin.site.urls),
      path('', include('main.front.urls')),
      path('dashboard/', include('main.dashboard.urls')),
      path('api/', include('api.urls')),
      ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.home_page),
    path('posts-in-category/<int:id>/', views.post_in_category),  # categoryaga tegishli postlarni chiqaradi
    path('posts-in-region/<int:id>/', views.post_in_region),  # regionaga tegishli postlarni chiqaradi
    # ---------comment-------------
    path('comment/<int:id>/', views.comment_post),  # comment
    # ---------post----------------
    path('post-list/', views.post_list),
    path('post-detail/<int:id>/', views.post_detail),
    # ---------category----------------
    path('category-list/', views.category_list),
    path('category-detail/<int:id>/', views.category_detail),
    # ---------region----------------
    path('region-list/', views.region_list),
    path('region-detail/<int:id>/', views.region_detail),
]

main/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    # category
    path('create_category/', views.create_category, name='create_category'),
    path('list_category/', views.list_category, name='list_category'),
    path('detail_category/<int:id>/', views.detail_category, name='detail_category'),
    path('edit_category/<int:id>/', views.edit_category, name='edit_category'),
    path('delete_category/<int:id>/', views.delete_category, name='delete_category'),

    # region
    path('create_region/', views.create_region, name='create_region'),
    path('list_region/', views.list_region, name='list_region'),
    path('detail_region/<int:id>/', views.detail_region, name='detail_region'),
    path('edit_region/<int:id>/', views.edit_region, name='edit_region'),
    path('delete_region/<int:id>/', views.delete_region, name='delete_region'),

    # register
    path('register/', views.register, name='register'),
    path('log-out/', views.log_out, name='log_out'),

    # news
    path('create_news/', views.create_news, name='create_news'),
    path('list_news/', views.list_news, name='list_news'),
    path('detail_news/<int:id>/', views.detail_news, name='detail_news'),
    path('edit_news/<int:id>/', views.edit_news, name='edit_news'),
    path('delete_news/<int:id>/', views.delete_news, name='delete_news'),
]

main/front/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('post_detail/<int:id>', views.post_detail, name='post_detail'),
    # path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('category/<int:id>/', views.category, name='category'),
    path('region/<int:id>', views.region, name='region_select')
    ]

main/front/views.py
from django.shortcuts import render
from .. import models


def index(request):
    categorys = models.Category.objects.all()
    regions = models.Region.objects.all()
    blog = models.Post.objects.all()
    head_blog = blog.filter().order_by('-id')[:2]
    context = {
        'category': categorys,
        'region': regions,
        'head_blog': head_blog,
    }
    #         head_blog.append(blog)
    return render(request, 'front/index.html', context)


# def single_post(request):
#     return render(request, 'front/single-post.html')
#

def contact(request):
    return render(request, 'front/contact.html')


def category(request, id):
    categorys = models.Category.objects.all()
    regions = models.Region.objects.all()
    categor = models.Category.objects.get(id=id)
    posts = models.Post.objects.filter(category=categor)
    context = {
        'category': categorys,
        'posts': posts,
        'region': regions
    }
    return render(request, 'front/catagory.html', context)


def region(request, id):
    region_item = models.Region.objects.get(id=id)
    category = models.Category.objects.all()
    region = models.Region.objects.all()
    posts = models.Post.objects.filter(region=region_item)
    context = {
        'region_item': region_item,
        'posts': posts,
        'region': region,
        'category': category
    }

    return render(request, 'front/region.html', context)


def post_detail(request, id):
    post_item = models.Post.objects.get(id=id)
    post_img = models.PostImg.objects.filter(post=id)
    # post_video = models.PostVideo.objects.get(id=id)
    category = models.Category.objects.all()
    region = models.Region.objects.all()
    context = {
        'post_item': post_item,
        'category': category,
        'region': region,
        'post_img': post_img,
        # 'post_video': post_video
    }
    return render(request, 'front/single-post.html', context)

templates/front/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title -->
    <title>Newsbox - Modern Magazine &amp; Newspaper HTML Template</title>

    <!-- Favicon -->
    <link rel="icon" href="{% static 'front/img/core-img/favicon.ico' %}">

    <!-- Stylesheet -->
    <link rel="stylesheet" href="{% static 'front/style.css' %}">

</head>

<body>
    <!-- Preloader -->
    <div class="preloader d-flex align-items-center justify-content-center">
        <div class="lds-ellipsis">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>

    <!-- ##### Header Area Start ##### -->
    <header class="header-area">
        <!-- Navbar Area -->
        <div class="newsbox-main-menu">
            <div class="classy-nav-container breakpoint-off">
                <div class="container-fluid">
                    <!-- Menu -->
                    <nav class="classy-navbar justify-content-between" id="newsboxNav">

                        <!-- Nav brand -->
                        <a href="index.html" class="nav-brand"><img src="{% static 'front/img/core-img/logo.png' %}" alt=""></a>

                        <!-- Navbar Toggler -->
                        <div class="classy-navbar-toggler">
                            <span class="navbarToggler"><span></span><span></span><span></span></span>
                        </div>

                        <!-- Menu -->
                        <div class="classy-menu">

                            <!-- Close Button -->
                            <div class="classycloseIcon">
                                <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                            </div>

                            <!-- Nav Start -->
                            <div class="classynav">
                                <ul>
                                    <li><a href="{% url 'main:index' %}">Bosh Sahifa</a></li>
                                    <li><a href="#">Region</a>
                                            <ul class="dropdown">
                                                {% for r in region %}
                                                <li><a href="{% url 'main:region_select' r.id %}">{{r.name}}</a></li>
                                                {% endfor %}
                                            </ul>
                                        
                                    </li>
                                    
                            
                                    <li><a href="#">Kategoria</a>
                                        <ul class="dropdown">
                                            {% for cate in category %}                                            
                                                 <li><a href="{% url 'main:category' cate.id %}">{{cate.name}}</a></li>
                                            {% endfor %}
                                        </ul>
                                    </li>
                                    <li><a href="#">Qo'shimcha</a>
                                        <ul class="dropdown">
                                            <li><a href="elements.html">Elements</a></li>
                                           
                                        </ul>
                                    </li>
                                    <li><a href="{% url 'main:contact' %}">Contact</a></li>
                                    <li><a href="{% url 'dashboard:register' %}">Kirish</a></li>
                                </ul>

                                <!-- Header Add Area -->
                              
                            </div>
                            <!-- Nav End -->

                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- ##### Header Area End ##### -->

    

    {% block content  %}

    {% endblock %}

    <!-- ##### Footer Area Start ##### -->
    <footer class="footer-area">
        <!-- Footer Logo -->
        <div class="footer-logo mb-100">
            <a href="index.html"><img src="img/core-img/logo.png" alt=""></a>
        </div>
        <!-- Footer Content -->
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="footer-content text-center">
                        <!-- Footer Nav -->
                        <div class="footer-nav">
                            <ul>
                                <li><a href="#">Contact Us</a></li>
                                <li><a href="#">Closed Captioning</a></li>
                                <li><a href="#">Site Map</a></li>
                            </ul>
                        </div>
                        <!-- Social Info -->
                        <div class="footer-social-info">
                            <a href="#" data-toggle="tooltip" data-placement="top" title="pinterest"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                            <a href="#" data-toggle="tooltip" data-placement="top" title="facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                            <a href="#" data-toggle="tooltip" data-placement="top" title="twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                            <a href="#" data-toggle="tooltip" data-placement="top" title="dribbble"><i class="fa fa-dribbble" aria-hidden="true"></i></a>
                            <a href="#" data-toggle="tooltip" data-placement="top" title="behance"><i class="fa fa-behance" aria-hidden="true"></i></a>
                            <a href="#" data-toggle="tooltip" data-placement="top" title="linkedin"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
                        </div>

                        <p class="mb-15">Nullam lacinia ex eleifend orci porttitor, suscipit interdum augue condimentum. Etiam pretium turpis eget nibh laoreet iaculis. Proin ac urna at lectus volutpat lobortis. Vestibulum venenatis iaculis diam vitae lobortis. Donec tincidunt viverra elit, sed consectetur est pr etium ac. Mauris nec mauris tellus. </p>

                        <!-- Copywrite Text -->
                        <p class="copywrite-text"><a href="#">
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- ##### Footer Area Start ##### -->

    <!-- ##### All Javascript Script ##### -->
    <!-- jQuery-2.2.4 js -->
    <script src="{% static 'front/js/jquery/jquery-2.2.4.min.js' %}"></script>
    <!-- Popper js -->
    <script src="{% static 'front/js/bootstrap/popper.min.js' %}"></script>
    <!-- Bootstrap js -->
    <script src="{% static 'front/js/bootstrap/bootstrap.min.js' %}"></script>
    <!-- All Plugins js -->
    <script src="{% static 'front/js/plugins/plugins.js' %}"></script>
    <!-- Active js -->
    <script src="{% static 'front/js/active.js' %}"></script>
    <script>
        n =  new Date();
        y = n.getFullYear();
        m = n.getMonth() + 1;
        d = n.getDate();
        document.getElementById("date-now").innerHTML = m + "/" + d + "/" + y;
    </script>
</body>

</html>

templates/front/contact.html
{% extends 'front/base.html' %}
{% block content  %}
{% load static %}
    <!-- ##### Contact Area Start ##### -->
    <div class="hero-contact-area bg-overlay clearfix" style="background-image: url('{% static 'front/img/bg-img/34.jpg' %}')">
        <div class="container-fluid h-100">
            <div class="row h-100 align-items-center">
                <div class="col-12 col-lg-7">
                    <!-- Post Content -->
                    <div class="post-content">
                        <p class="tag"><span>Featured</span></p>
                        <p class="post-title">China's economy shows signs of slowing.</p>
                        <div class="d-flex align-items-center">
                            <span class="post-date mr-30">June 20, 2018</span>
                            <span class="post-date">By Michael Smith</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Contact Area End ##### -->

    <!-- ##### Contact Area Start ##### -->
    <section class="contact-area section-padding-100">
        <div class="container">
            <div class="row justify-content-center">

                <div class="col-12 col-lg-8">
                    <div class="contact-content mb-100">

                        <!-- Logo -->
                        <a href="#" class="d-block mb-50"><img src="{% static 'front/img/core-img/logo.png' %}" alt=""></a>

                        <!-- Single Contact Info -->
                        <div class="single-contact-info d-flex align-items-center">
                            <div class="icon mr-15">
                                <img src="{% static 'front/img/core-img/map-pin.png' %}" alt="">
                            </div>
                            <p>1481 Creekside Lane Avila Beach, CA 931</p>
                        </div>

                        <!-- Single Contact Info -->
                        <div class="single-contact-info d-flex align-items-center">
                            <div class="icon mr-15">
                                <img src="{% static 'front/img/core-img/smartphone.png' %}" alt="">
                            </div>
                            <p>+53 345 7953 32453</p>
                        </div>

                        <!-- Single Contact Info -->
                        <div class="single-contact-info d-flex align-items-center">
                            <div class="icon mr-15">
                                <img src="{% static 'front/img/core-img/paper-plane.png' %}" alt="">
                            </div>
                            <p>yourmail@gmail.com</p>
                        </div>

                        <!-- Contact Social Info -->
                        <div class="contact-social-info mt-50 mb-70">
                            <a href="#" data-toggle="tooltip" data-placement="top" title="Pinterest"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                            <a href="#" data-toggle="tooltip" data-placement="top" title="Facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                            <a href="#" data-toggle="tooltip" data-placement="top" title="Twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                            <a href="#" data-toggle="tooltip" data-placement="top" title="Dribbble"><i class="fa fa-dribbble" aria-hidden="true"></i></a>
                            <a href="#" data-toggle="tooltip" data-placement="top" title="Behance"><i class="fa fa-behance" aria-hidden="true"></i></a>
                            <a href="#" data-toggle="tooltip" data-placement="top" title="Linkedin"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
                        </div>

                        <!-- Contact Form Area -->
                        <div class="contact-form-area mb-70">
                            <h4 class="mb-50">Get In Touch</h4>

                            <form action="#" method="post">
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <input type="text" class="form-control" id="name" placeholder="Name">
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <input type="email" class="form-control" id="email" placeholder="E-mail">
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-group">
                                            <input type="text" class="form-control" id="subject" placeholder="Subject">
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-group">
                                            <textarea name="message" class="form-control" id="message" cols="30" rows="10" placeholder="Message"></textarea>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <button class="btn newsbox-btn mt-30" type="submit">Send</button>
                                    </div>
                                </div>
                            </form>
                        </div>

                        <!-- ##### Google Maps ##### -->
                        <div class="map-area mb-100">
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d22236.40558254599!2d-118.25292394686001!3d34.057682914027104!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80c2c75ddc27da13%3A0xe22fdf6f254608f4!2z4Kay4Ka4IOCmj-CmnuCnjeCmnOCnh-CmsuCnh-CmuCwg4KaV4KeN4Kav4Ka-4Kay4Ka_4Kar4KeL4Kaw4KeN4Kao4Ka_4Kav4Ka84Ka-LCDgpq7gpr7gprDgp43gppXgpr_gpqgg4Kav4KeB4KaV4KeN4Kak4Kaw4Ka-4Ka34KeN4Kaf4KeN4Kaw!5e0!3m2!1sbn!2sbd!4v1532328708137" allowfullscreen></iframe>
                        </div>

                    </div>
                </div>

                <div class="col-12 col-sm-9 col-md-6 col-lg-4">

                    <!-- Newsletter Widget -->
                    <div class="single-widget-area newsletter-widget mb-30">
                        <h4>Subscribe to our newsletter</h4>
                        <form action="#" method="post">
                            <input type="email" name="nl-email" id="nlemail" placeholder="Your E-mail">
                            <button type="submit" class="btn newsbox-btn w-100">Subscribe</button>
                        </form>
                        <p class="mt-30">Nullam lacinia ex eleifend orci porttitor, suscipit interdum augue condimentum. Etiam pretium turpis eget nibh . volutpat lobortis.</p>
                    </div>

                    <!-- Add Widget -->
                    <div class="single-widget-area add-widget mb-30">
                        <a href="#">
                                <img src="img/bg-img/add3.png" alt="">
                            </a>
                    </div>

                    <!-- Latest News Widget -->
                    <div class="single-widget-area news-widget mb-30">
                        <h4>Latest News</h4>

                        <!-- Single News Area -->
                        <div class="single-blog-post d-flex style-4 mb-30">
                            <!-- Blog Thumbnail -->
                            <div class="blog-thumbnail">
                                <a href="#"><img src="img/bg-img/16.jpg" alt=""></a>
                            </div>

                            <!-- Blog Content -->
                            <div class="blog-content">
                                <span class="post-date">June 20, 2018</span>
                                <a href="#" class="post-title">Nearly a quarter have no emergency savings</a>
                            </div>
                        </div>

                        <!-- Single News Area -->
                        <div class="single-blog-post d-flex style-4 mb-30">
                            <!-- Blog Thumbnail -->
                            <div class="blog-thumbnail">
                                <a href="#"><img src="img/bg-img/17.jpg" alt=""></a>
                            </div>

                            <!-- Blog Content -->
                            <div class="blog-content">
                                <span class="post-date">June 20, 2018</span>
                                <a href="#" class="post-title">Nearly a quarter have no emergency savings</a>
                            </div>
                        </div>

                        <!-- Single News Area -->
                        <div class="single-blog-post d-flex style-4 mb-30">
                            <!-- Blog Thumbnail -->
                            <div class="blog-thumbnail">
                                <a href="#"><img src="img/bg-img/18.jpg" alt=""></a>
                            </div>

                            <!-- Blog Content -->
                            <div class="blog-content">
                                <span class="post-date">June 20, 2018</span>
                                <a href="#" class="post-title">Top bitcoin exchange says over $30 million stolen</a>
                            </div>
                        </div>

                        <!-- Single News Area -->
                        <div class="single-blog-post d-flex style-4 mb-30">
                            <!-- Blog Thumbnail -->
                            <div class="blog-thumbnail">
                                <a href="#"><img src="img/bg-img/19.jpg" alt=""></a>
                            </div>

                            <!-- Blog Content -->
                            <div class="blog-content">
                                <span class="post-date">June 20, 2018</span>
                                <a href="#" class="post-title">Top bitcoin exchange says over $30 million stolen</a>
                            </div>
                        </div>

                        <!-- Single News Area -->
                        <div class="single-blog-post d-flex style-4 mb-30">
                            <!-- Blog Thumbnail -->
                            <div class="blog-thumbnail">
                                <a href="#"><img src="img/bg-img/20.jpg" alt=""></a>
                            </div>

                            <!-- Blog Content -->
                            <div class="blog-content">
                                <span class="post-date">June 20, 2018</span>
                                <a href="#" class="post-title">Dow falls 287 points as trade war fears escalate</a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>
    <!-- ##### Contact Area End ##### -->

    {% endblock %}

templates/front/region.html
{% extends 'front/base.html' %}
{% block content  %}
{% load static %}

    <!-- ##### Catagory Featured Area Start ##### -->
    <div class="catagory-featured-post bg-overlay clearfix" style="background-image: url(' {% static 'front/img/bg-img/23.jpg' %} ')">
        <div class="container-fluid h-100">
            <div class="row h-100 align-items-center">
                <div class="col-12 col-lg-9">
                    <!-- Post Content -->
                    <div class="post-content">
                        <p class="tag"><span>{{region_item.name}}</span></p>
                        <a href="#" class="post-title">Xududlar bo'yicha <br>xabarlar</a>
                        <span class="post-date">
                            <p id="date-now"></p>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Catagory Featured Area End ##### -->
    <!-- ##### Top News Area Start ##### -->
    <div class="top-news-area section-padding-100">
        <div class="container">
            <div class="row">
                {% for p in posts %}
                <!-- Single News Area -->
                <div class="col-12 col-sm-6 col-lg-4">
                    <div class="single-blog-post style-2 mb-5">
                        <!-- Blog Thumbnail -->
                        <div class="blog-thumbnail">
                            <a href="{% url 'main:post_detail' p.id %}"><img src="{{p.banner.url}}" alt=""></a>
                        </div>

                        <!-- Blog Content -->
                        <div class="blog-content">
                            <span class="post-date">{{p.date}}</span>
                            <a href="{% url 'main:post_detail' p.id %}" class="post-title">{{p.title}}</a>
                            <a href="#" class="post-author">{{p.author}}</a>
                        </div>
                    </div>
                </div>
                {% endfor %}

                <!-- <div class="col-12">
                    <div class="load-more-button text-center">
                        <a href="#" class="btn newsbox-btn">Load More</a>
                    </div>
                </div> -->

            </div>
        </div>
    </div>
    <!-- ##### Top News Area End ##### -->

    <!-- ##### Add Area Start ##### -->
    <div class="big-add-area mb-100">
        <div class="container-fluid">
            <a href="#"><img src="{% static 'front/img/bg-img/add2.png' %}" alt=""></a>
        </div>
    </div>
    <!-- ##### Add Area End ##### -->

{% endblock %}